version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: md_app
    ports:
      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data